In [1]:
import matplotlib.pyplot as plt 
import seaborn as sns
import sklearn
import pandas as pd
import numpy as np
titanic= sns.load_dataset("titanic")


In [6]:
from sklearn.preprocessing import OneHotEncoder
enc=OneHotEncoder()
ohe_town=enc.fit_transform(titanic["embark_town"].values.reshape(-1,1))

ValueError: Input contains NaN

In [8]:
print(ohe_town)

NameError: name 'ohe_town' is not defined

In [9]:

titanic["alive"]=titanic["alive"].replace(to_replace='yes',value=1)
titanic["alive"]=titanic["alive"].replace(to_replace='no',value=0)
titanic["adult_male"]=titanic["adult_male"].replace(to_replace=True,value=1)
titanic["adult_male"]=titanic["adult_male"].replace(to_replace=False,value=0)
titanic["sex"]=titanic["sex"].replace(to_replace='male',value=1)
titanic["sex"]=titanic["sex"].replace(to_replace='female',value=0)
titanic["who"]=titanic["who"].replace(to_replace='man',value=1)
titanic["who"]=titanic["who"].replace(to_replace='woman',value=2)
titanic["who"]=titanic["who"].replace(to_replace='child',value=3)
titanic=titanic.drop(columns=["class","embarked","deck","alone"],axis=1)






In [11]:
titanic.head()

survived  pclass  sex   age  sibsp  parch     fare  who  adult_male  \
0         0       3    1  22.0      1      0   7.2500    1         1.0   
1         1       1    0  38.0      1      0  71.2833    2         0.0   
2         1       3    0  26.0      0      0   7.9250    2         0.0   
3         1       1    0  35.0      1      0  53.1000    2         0.0   
4         0       3    1  35.0      0      0   8.0500    1         1.0   

   embark_town  alive  
0  Southampton      0  
1    Cherbourg      1  
2  Southampton      1  
3  Southampton      1  
4  Southampton      0

In [18]:
categories=list(titanic['embark_town'].values)
cat_list = []
for i in categories:
    i=str(i)
    temp = ""
    # consider we have text like this "Math & Science, Warmth, Care & Hunger"
    for j in i.split(','): # it will split it in three parts ["Math & Science", "Warmth", "Care & Hunger"]
        if 'The' in j.split(): # this will split each of the catogory based on space "Math & Science"=> "Math","&", "Science"
            j=j.replace('The','') # if we have the words "The" we are going to replace it with ''(i.e removing 'The')
        j = j.replace(' ','') # we are placeing all the ' '(space) with ''(empty) ex:"Math & Science"=>"Math&Science"
        temp+=j.strip()+" " #" abc ".strip() will return "abc", remove the trailing spaces
        temp = temp.replace('&','_') # we are replacing the & value into 
    cat_list.append(temp.strip())
from collections import Counter
my_counter = Counter()
for word in titanic['embark_town'].values:
    word=str(word)
    my_counter.update(word.split())

In [19]:
titanic['clean_categories'] = cat_list
titanic.drop(['embark_town'], axis=1, inplace=True)
titanic.head(2)

survived  pclass  sex   age  sibsp  parch     fare  who  adult_male  alive  \
0         0       3    1  22.0      1      0   7.2500    1         1.0      0   
1         1       1    0  38.0      1      0  71.2833    2         0.0      1   

  clean_categories  
0      Southampton  
1        Cherbourg

In [20]:
cat_dict = dict(my_counter)
sorted_cat_dict = dict(sorted(cat_dict.items(), key=lambda kv: kv[1]))

In [21]:
for i, j in sorted_cat_dict.items():
    print("{:20} :{:10}".format(i,j))

nan                  :         2
Queenstown           :        77
Cherbourg            :       168
Southampton          :       644


In [23]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(vocabulary=list(sorted_cat_dict.keys()), lowercase=False, binary=True)
vectorizer.fit(titanic['clean_categories'].values)
print(vectorizer.get_feature_names())


categories_one_hot = vectorizer.transform(titanic['clean_categories'].values)
print("Shape of matrix after one hot encodig ",categories_one_hot.shape)

['nan', 'Queenstown', 'Cherbourg', 'Southampton']
Shape of matrix after one hot encodig  (891, 4)


In [27]:
print(categories_one_hot)

  (0, 3)	1
  (1, 2)	1
  (2, 3)	1
  (3, 3)	1
  (4, 3)	1
  (5, 1)	1
  (6, 3)	1
  (7, 3)	1
  (8, 3)	1
  (9, 2)	1
  (10, 3)	1
  (11, 3)	1
  (12, 3)	1
  (13, 3)	1
  (14, 3)	1
  (15, 3)	1
  (16, 1)	1
  (17, 3)	1
  (18, 3)	1
  (19, 2)	1
  (20, 3)	1
  (21, 3)	1
  (22, 1)	1
  (23, 3)	1
  (24, 3)	1
  :	:
  (866, 2)	1
  (867, 3)	1
  (868, 3)	1
  (869, 3)	1
  (870, 3)	1
  (871, 3)	1
  (872, 3)	1
  (873, 3)	1
  (874, 2)	1
  (875, 2)	1
  (876, 3)	1
  (877, 3)	1
  (878, 3)	1
  (879, 2)	1
  (880, 3)	1
  (881, 3)	1
  (882, 3)	1
  (883, 3)	1
  (884, 3)	1
  (885, 1)	1
  (886, 3)	1
  (887, 3)	1
  (888, 3)	1
  (889, 2)	1
  (890, 1)	1


In [28]:
from sklearn.preprocessing import StandardScaler


price_scalar = StandardScaler()
price_scalar.fit(titanic['age'].values.reshape(-1,1)) # finding the mean and standard deviation of this data
print(f"Mean : {price_scalar.mean_[0]}, Standard deviation : {np.sqrt(price_scalar.var_[0])}")

# Now standardize the data with above maen and variance.
price_standardized = price_scalar.transform(titanic['age'].values.reshape(-1, 1))

Mean : 29.69911764705882, Standard deviation : 14.516321150817316


In [29]:
price_standardized

array([[-0.53037664],
       [ 0.57183099],
       [-0.25482473],
       [ 0.36516706],
       [ 0.36516706],
       [        nan],
       [ 1.67403863],
       [-1.90813618],
       [-0.18593675],
       [-1.08148046],
       [-1.77036023],
       [ 1.94959054],
       [-0.6681526 ],
       [ 0.64071897],
       [-1.08148046],
       [ 1.74292661],
       [-1.90813618],
       [        nan],
       [ 0.08961515],
       [        nan],
       [ 0.36516706],
       [ 0.29627909],
       [-1.01259248],
       [-0.11704878],
       [-1.49480832],
       [ 0.57183099],
       [        nan],
       [-0.73704057],
       [        nan],
       [        nan],
       [ 0.70960695],
       [        nan],
       [        nan],
       [ 2.50069435],
       [-0.11704878],
       [ 0.8473829 ],
       [        nan],
       [-0.59926462],
       [-0.80592855],
       [-1.08148046],
       [ 0.70960695],
       [-0.18593675],
       [        nan],
       [-1.83924821],
       [-0.73704057],
       [  

In [30]:



fare_scalar = StandardScaler()
fare_scalar.fit(titanic['fare'].values.reshape(-1,1)) # finding the mean and standard deviation of this data
print(f"Mean : {fare_scalar.mean_[0]}, Standard deviation : {np.sqrt(fare_scalar.var_[0])}")

# Now standardize the data with above maen and variance.
fare_standardized = fare_scalar.transform(titanic['fare'].values.reshape(-1, 1))

Mean : 32.204207968574636, Standard deviation : 49.6655344447741


In [31]:
fare_standardized

array([[-5.02445171e-01],
       [ 7.86845294e-01],
       [-4.88854258e-01],
       [ 4.20730236e-01],
       [-4.86337422e-01],
       [-4.78116429e-01],
       [ 3.95813561e-01],
       [-2.24083121e-01],
       [-4.24256141e-01],
       [-4.29555021e-02],
       [-3.12172378e-01],
       [-1.13845709e-01],
       [-4.86337422e-01],
       [-1.87093118e-02],
       [-4.90279793e-01],
       [-3.26266659e-01],
       [-6.19988892e-02],
       [-3.86670720e-01],
       [-2.85997284e-01],
       [-5.02948539e-01],
       [-1.24919787e-01],
       [-3.86670720e-01],
       [-4.86756223e-01],
       [ 6.63597416e-02],
       [-2.24083121e-01],
       [-1.64441595e-02],
       [-5.02948539e-01],
       [ 4.64700108e+00],
       [-4.89776426e-01],
       [-4.89442190e-01],
       [-9.02720170e-02],
       [ 2.30172882e+00],
       [-4.92377828e-01],
       [-4.37007438e-01],
       [ 1.00606170e+00],
       [ 3.98582080e-01],
       [-5.02863973e-01],
       [-4.86337422e-01],
       [-2.8

In [32]:



class_scalar = StandardScaler()
class_scalar.fit(titanic['pclass'].values.reshape(-1,1)) # finding the mean and standard deviation of this data
print(f"Mean : {class_scalar.mean_[0]}, Standard deviation : {np.sqrt(class_scalar.var_[0])}")

# Now standardize the data with above maen and variance.
class_standardized = fare_scalar.transform(titanic["pclass"].values.reshape(-1, 1))

Mean : 2.308641975308642, Standard deviation : 0.8356019334795166


In [33]:
class_standardized

array([[-0.58801759],
       [-0.62828697],
       [-0.58801759],
       [-0.62828697],
       [-0.58801759],
       [-0.58801759],
       [-0.62828697],
       [-0.58801759],
       [-0.58801759],
       [-0.60815228],
       [-0.58801759],
       [-0.62828697],
       [-0.58801759],
       [-0.58801759],
       [-0.58801759],
       [-0.60815228],
       [-0.58801759],
       [-0.60815228],
       [-0.58801759],
       [-0.58801759],
       [-0.60815228],
       [-0.60815228],
       [-0.58801759],
       [-0.62828697],
       [-0.58801759],
       [-0.58801759],
       [-0.58801759],
       [-0.62828697],
       [-0.58801759],
       [-0.58801759],
       [-0.62828697],
       [-0.62828697],
       [-0.58801759],
       [-0.60815228],
       [-0.62828697],
       [-0.62828697],
       [-0.58801759],
       [-0.58801759],
       [-0.58801759],
       [-0.58801759],
       [-0.58801759],
       [-0.60815228],
       [-0.58801759],
       [-0.60815228],
       [-0.58801759],
       [-0

In [34]:
from scipy.sparse import hstack
# with the same hstack function we are concatinating a sparse matrix and a dense matirx :)
X = hstack((categories_one_hot, fare_standardized, class_standardized, price_standardized))
X.shape

(891, 7)

In [39]:
X=X.fillna(X.mean())

AttributeError: fillna not found

In [36]:
from sklearn.manifold import TSNE
model=TSNE(n_components=2,random_state=0,perplexity=30,n_iter=100)
tsne_data=model.fit_transform(X.toarray())


ValueError: Input contains NaN, infinity or a value too large for dtype('float64').